# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 'Site Title'
email: example@gmail.com
description: 'Site description'
baseurl:
url: 'https://example.com'
twitter_username:
github_username:
google_analytics:
disqus:
  shortname:

assets:
  autoprefixer:
    browsers:
      - 'last 2 versions'
      - '> 5%'
      - 'IE 9'
  autowrite: true
  cache: '.asset-cache'
  cache_type: 'memory | filesystem | default: filesystem'
  compress:
    css: 'false | true | default - development: false, production: true'
    js: 'false | true | default - development: false, production: true'
  digest: true
  features:
    liquid: 'true | false | default: false'
    integrity: 'true | false | default: false'
    # This will add height and width attributes for an img tag.
    automatic_img_size: 'true | false | n(fixnum): 2,4,6,8 | default: true'
    # This will add the digest path as an alt attribute for an img tag.
    automatic_img_alt: 'true | false | default: true'
  image_optim:
    default:
      verbose: true
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: /assets
  assets:
    - assets/stylesheets
    - assets/fonts
    - assets/images
    - assets/javascripts
    - assets/icons
  sources:
    - _assets/css
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
    - _assets/icons

# Permalink structure and pagination options
permalink: pretty
paginate: 10
paginate_path: 'page:num'
excerpt_separator:

# Server Config options
# https://github.com/RobertDeRose/jekyll-livereload
livereload: true

# Build settings
markdown: kramdown
highlighter: true

plugins:
  - jekyll-analytics
  - jekyll-assets
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .asset-cache
  - .sass-cache
  - README.md
  - package.json
