# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Chris Anthony
email: CTAnthny@gmail.com
description: Portfolio of work
baseurl: "" # the subpath of your site, e.g. /blog
url: https://ctanthny.com # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ""
github_username:  CTAnthny

assets:
  autoprefixer:
    browsers: ["last 2 versions","> 5%","IE 9"]
  autowrite: true
  cache: false | directory | default: .asset-cache
  cache_type: memory | filesystem | default: filesystem
  cdn:
  compress:
    css: false | true | default - development: false, production: true
    js: false | true | default - development: false, production: true
  digest: true
  features:
    liquid: true | false | default: false
    integrity: true | false | default: false
    # This will add height and width attributes for an img tag.
    automatic_img_size: true | false | n(fixnum): 2,4,6,8 | default: true
    # This will add the digest path as an alt attribute for an img tag.
    automatic_img_alt : true | false | default: true
  image_optim:
    default:
      verbose: true
    zero_png:
      advpng:
        level: 0
      optipng:
        level: 0
      pngout:
        strategy: 4
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"  
  assets:
    - assets/css
    - assets/fonts
    - assets/images
    - assets/javascript
    - assets/image
    - assets/img
    - assets/js
  sources:
    - _assets/css
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
    - _assets/img
    - _assets/js


jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-123-456          # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking

# Permalink structure and pagination options
permalink: pretty
paginate: 10
paginate_path: 'page:num'
excerpt_separator: ''

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-analytics
  - jekyll-assets
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
